"""Add role_change_audits table

Revision ID: 63718ff273fb
Revises: 7e73907ec1db
Create Date: 2026-09-07 16:47:18.863600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63718ff273fb'
down_revision: Union[str, None] = '7e73907ec1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_change_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('old_role', sa.String(length=20), nullable=False),
    sa.Column('new_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_change_audits_changed_by'), 'role_change_audits', ['changed_by'], unique=False)
    op.create_index(op.f('ix_role_change_audits_target_user_id'), 'role_change_audits', ['target_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_change_audits_target_user_id'), table_name='role_change_audits')
    op.drop_index(op.f('ix_role_change_audits_changed_by'), table_name='role_change_audits')
    op.drop_table('role_change_audits')
    # ### end Alembic commands ###