"""Add file_encryption_keys table

Revision ID: 7e73907ec1db
Revises: 9f6e7c0ee769
Create Date: 2026-09-02 08:05:37.244592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e73907ec1db'
down_revision: Union[str, None] = '9f6e7c0ee769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_encryption_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_material', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_encryption_keys')
    # ### end Alembic commands ###